In [1]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
len(x), x.shape

(4, torch.Size([4]))

In [4]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [5]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [6]:
B = torch.tensor([[1,2,3], [2,0,4], [3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [7]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [8]:
A = torch.arange(20).reshape(5, 4)
B = A.clone()

A, A + B

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22],
         [24, 26, 28, 30],
         [32, 34, 36, 38]]))

In [9]:
A * B

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])

In [12]:
A
A_sum_axis0 = A.sum(axis = 0)
A_sum_axis0


tensor([40, 45, 50, 55])

In [13]:
A.sum()

tensor(190)